### ISSUE TITLE
ORTE integration hang

### ISSUE THREAD

**Issue by artpol84** [pmix/master#17]
@rhc54 
Hello,
When running ring_c at 128 nodes 28 ppn I sometimes see that mpirun launch hangs if I use **tcp** BTL. I never saw this with **openib** so far. SLURM **PMIx/PMI2** launches are this error free as well. 
I haven't looked into all processes but all inspected ones was sitting in the Fence:
**rank = 0**
```
(gdb) bt
#0  0x00000037694ac9fd in nanosleep () from /lib64/libc.so.6
#1  0x00000037694e1b54 in usleep () from /lib64/libc.so.6
#2  0x00007ffff67cb330 in OPAL_PMIX_PMIX1XX_PMIx_Fence (procs=0x0, nprocs=0, info=0x7fffffffca10, ninfo=1)
    at src/client/pmix_client_fence.c:100
#3  0x00007ffff69fbf1c in pmix1_fence (procs=0x0, collect_data=1) at pmix1_client.c:306
#4  0x00007ffff7cd03e7 in ompi_mpi_init (argc=1, argv=0x7fffffffced8, requested=0, provided=0x7fffffffcd58) at runtime/ompi_mpi_init.c:644
#5  0x00007ffff7d069d5 in PMPI_Init (argc=0x7fffffffcdbc, argv=0x7fffffffcdb0) at pinit.c:66
#6  0x000000000040086e in main (argc=1, argv=0x7fffffffced8) at ring_c.c:19
```
**rank = 27**
```
(gdb) bt
#0  0x00000037694ac9fd in nanosleep () from /lib64/libc.so.6
#1  0x00000037694e1b54 in usleep () from /lib64/libc.so.6
#2  0x00007ffff67cb330 in OPAL_PMIX_PMIX1XX_PMIx_Fence (procs=0x0, nprocs=0, info=0x7fffffffca10, ninfo=1)
    at src/client/pmix_client_fence.c:100
#3  0x00007ffff69fbf1c in pmix1_fence (procs=0x0, collect_data=1) at pmix1_client.c:306
#4  0x00007ffff7cd03e7 in ompi_mpi_init (argc=1, argv=0x7fffffffced8, requested=0, provided=0x7fffffffcd58) at runtime/ompi_mpi_init.c:644
#5  0x00007ffff7d069d5 in PMPI_Init (argc=0x7fffffffcdbc, argv=0x7fffffffcdb0) at pinit.c:66
#6  0x000000000040086e in main (argc=1, argv=0x7fffffffced8) at ring_c.c:19
```
I haven't had a time to investigate that more deeply yet.

**Comment by rhc54** [comment]
@artpol84 I'm pretty sure this isn't true any more - can you confirm and close?

**Comment by artpol84** [comment]
@rhc54 Since the cluster I was working on has changed I was unable to reproduce exactly the same environment. But in new environment 96 procs 28 ppn was running fine.
